config/routes.rb
CmsRails::Application.routes.draw do

   get "signup" => "signup#index"
  post "signup" => "signup#signup"

  resources :programs, :as => 'flow_programs', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
      get 'sections'
      get 'controls'
    end
  end

  resources :directives, :as => 'flow_directives', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'export_controls'
      get 'export'
      get 'sections'
      get 'section_controls'
      get 'control_sections'
      get 'category_controls'
      get 'delete'
      get 'import_controls'
      post 'import_controls'
      get 'import'
      post 'import'
    end
  end

  resources :program_directives, :as => 'flow_program_directives', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :cycles, :as => 'flow_cycles', :only => [:show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :sections, :as => 'flow_sections', :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :controls, :as => 'flow_controls', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'sections'
      get 'implemented_controls'
      get 'implementing_controls'
      get 'systems'
      get 'risks'
      get 'delete'
    end
  end

  resources :systems, :as => 'flow_systems', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :system_systems, :as => 'flow_system_systems', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :system_controls, :as => 'flow_system_controls', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :transactions, :as => 'flow_transactions', :only => [:new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :products, :as => 'flow_products', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :org_groups, :as => 'flow_org_groups', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :facilities, :as => 'flow_facilities', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :markets, :as => 'flow_markets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :projects, :as => 'flow_projects', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :data_assets, :as => 'flow_data_assets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risky_attributes, :as => 'flow_risky_attributes', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risks, :as => 'flow_risks', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :control_risks, :as => 'flow_control_risks', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :risk_risky_attributes, :as => 'flow_risk_risky_attributes', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :accounts, :as => 'flow_accounts' do
    member do
      get 'delete'
    end
  end

  resources :people, :as => 'flow_people', :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :object_people, :as => 'flow_object_people', :only => [:index, :create, :update, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :documents, :as => 'flow_documents' do
    member do
      get 'delete'
    end
  end

  resources :object_documents, :as => 'flow_object_documents', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :categories, :as => 'flow_categories' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :options, :as => 'flow_options' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :categorizations, :as => 'flow_categorizations', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :relationships, :as => 'flow_relationships', :only => [:index, :create] do
    collection do
      get 'related_objects'
      get 'list_edit'
      get 'related'
      get 'graph'
    end
  end

  resources :pbc_lists, :as => 'flow_pbc_lists', :only => [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
      get 'import'
      post 'import'
      get 'export'
      get 'export_responses'
    end
  end

  resources :requests, :as => 'flow_requests', :only => [:new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :responses, :as => 'flow_responses', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :population_samples, :as => 'flow_population_samples', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :meetings, :as => 'flow_meetings', :only => [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :control_assessments, :as => 'flow_control_assessments', :only => [] do
    member do
      post 'rotate'
    end
  end

  match 'programs_dash' => 'programs_dash#index'
  match 'admin_dash' => 'admin_dash#index'

  get 'admin_dash/:action' => 'admin_dash'
  get 'design/templates/:name' => 'design#templates'
  get 'design/:action' => 'design'

  get "mapping/show/:program_id" => 'mapping#show', :as => 'mapping_program'
  get 'mapping_section_dialog/:section_id' => 'mapping#section_dialog', :as => 'mapping_section_dialog'
  post "mapping/map_rcontrol"
  post "mapping/map_ccontrol"
  put "mapping/update/:section_id" => 'mapping#update', :as => 'mapping_update'

  match 'help/:slug' => 'help#show', :as => :help
  post 'help' => 'help#edit', :as => :update_help

  if !Rails.env.test? && CmsRails::Application.sso_callback_url
    match 'sso/new' => 'sso#new', :as => 'login'
    match CmsRails::Application.sso_callback_url => "sso#callback"
    match 'sso/destroy' => 'sso#destroy', :as => 'logout'
  else
    match 'login' => 'user_sessions#login', :as => 'login'
    match 'user_sessions/destroy' => 'user_sessions#destroy', :as => 'logout'
    match 'user_sessions/create' => 'user_sessions#create'
  end

  match 'document/:action' => 'document'

  match 'evidence/index' => 'evidence#index'
  match 'evidence/show_closed_control/:system_id/:control_id' => 'evidence#show_closed_control'
  match 'evidence/show_control/:system_id/:control_id' => 'evidence#show_control'
  match 'evidence/new/:system_id/:control_id/:descriptor_id' => 'evidence#new'
  match 'evidence/new_gdoc/:system_id/:control_id/:descriptor_id' => 'evidence#new_gdoc'
  match 'evidence/attach/:system_id/:control_id/:descriptor_id' => 'evidence#attach'
  match 'evidence/show/:document_id' => 'evidence#show'
  match 'evidence/update/:document_id' => 'evidence#update'
  match 'evidence/destroy/:system_id/:control_id/:document_id' => 'evidence#destroy'
  match 'evidence/review/:document_id/:value' => 'evidence#review'

  root :to => "welcome#index"
  match 'about' => 'welcome#about', :as => 'about'
  match 'placeholder' => 'welcome#placeholder', :as => 'placeholder'
  match 'login_dispatch' => 'welcome#login_dispatch', :as => 'login_dispatch'
  get 'welcome/reload'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  include AuthoredModel

  # Note: No accessible attributes - you pretty much
  # never want to allow changes to these without authorization.

  belongs_to :source, :polymorphic => true
  belongs_to :destination, :polymorphic => true
  belongs_to :relationship_type

  is_versioned_ext

  scope :manages, where(:relationship_type_id => 'manager_of')


  def self.related_objects_for_delete(object)
    object_type = object.class.name
    object_id = object.id

    table = arel_table

    src_query = table[:source_type].eq(object_type).and(table[:source_id].eq(object.id))
    dst_query = table[:destination_type].eq(object_type).and(table[:destination_id].eq(object.id))

    objects = {}

    where(src_query).all.each do |rel|
      objects[rel.destination_type] ||= []
      objects[rel.destination_type] << rel.destination
    end

    where(dst_query).all.each do |rel|
      objects[rel.source_type] ||= []
      objects[rel.source_type] << rel.source
    end

    objects
  end

  def self.index_query(params, base_query=nil)
    if base_query.nil?
      base_query = self
    end
    objects = base_query

    if params[:relationship_type].present?
      objects = objects.where(:relationship_type_id => params[:relationship_type])
    end

    if params[:object_type].present?
      # Search for 'object' on either side of the relationship

      table = self.arel_table #Arel::Table.new(:relationships)
      forward_query = table[:source_type].eq(params[:object_type])
      reverse_query = table[:destination_type].eq(params[:object_type])

      if params[:object_id]
        # Search with object ID

        forward_query = forward_query.and(
          table[:source_id].eq(params[:object_id]))
        reverse_query = reverse_query.and(
          table[:destination_id].eq(params[:object_id]))
      end

      if params[:other_type].present?
        # Search for 'other' on whatever side 'object' is not on

        forward_query = forward_query.and(
          table[:destination_type].eq(params[:other_type]))
        reverse_query = reverse_query.and(
          table[:source_type].eq(params[:other_type]))

        if params[:other_id]
          # Search with object_type, other_type, object_id, other_id

          forward_query = forward_query.and(
            table[:destination_id].eq(params[:other_id]))
          reverse_query = reverse_query.and(
            table[:source_id].eq(params[:other_id]))
        end
      end

      objects = objects.where(forward_query.or(reverse_query))
    else
      if params[:source_type].present?
        objects = objects.where(:source_type => params[:source_type])

        if params[:source_id].present?
          objects = objects.where(:source_id => params[:source_id])
        end
      end

      if params[:destination_type].present?
        objects = objects.where(:destination_type => params[:destination_type])

        if params[:destination_id].present?
          objects = objects.where(:destination_id => params[:destination_id])
        end
      end
    end

    return objects
  end
  
  def other_id(object_id)
    source_id == object_id ? destination_id : source_id
  end
end

app/models/relationship_type.rb
class RelationshipType < ActiveRecord::Base
  include AuthoredModel
  include SanitizableAttributes

  # attr_accessible :title, :body
  self.primary_key = 'relationship_type'

  has_many :relationships

  is_versioned_ext

  sanitize_attributes :description
end

app/views/relationships/_list_form.haml
-content_for :modal_title do
  =context[:title]

%script#relationship_option_data{ :type => 'text/html' }
  .object-info
    %span.name <%= object.title %>
    %span.option <%= object.slug %>

%script#relationship_selected{ :type => 'text/html', :'data-member' => 'relationship', :'data-type' => '', :'data-start_date' => '', :'data-stop_date' => '' }
  %li{ :'data-id' => '<%= id %>', :'data-object-id' => '<%= object.id %>', :'data-name' => '<%= object.name %>', :'data-company' => '<%= object.company %>' }
    .row-fluid
      .span6.object_info{ :'data-template-id' => 'relationship_option_data' }
      .span6.actions
        %span.state
        .pull-right
          %input{ :type => 'hidden', :name => 'items[<%= id %>][id]', :value => '<% if (id.toString().substr(0,3) != "new") { %><%= id %><% } %>'.html_safe }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][relationship_type]', :value => context[:relationship_type] }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][related_type]', :value => context[:related_type] }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][related_id]', :value => '<%= object.id %>' }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][related_side]', :value => context[:related_side] }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][object_id]', :value => context[:object_id] }
          %input{ :type => 'hidden', :name => 'items[<%= id %>][object_type]', :value => context[:object_type] }
          %input._destroy{ :type => 'hidden', :name => 'items[<%= id %>][_destroy]', :value => '' }
          %a.widgetbtn.btn.btn-mini{ :href => url_for(:action => :edit, :controller => context[:related_real_type].underscore.pluralize, :id => '<%=object.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.btn.btn-mini{ :href => '#', :'data-toggle' => 'selector-list-remove' }
            %i.grcicon-remove

%script#relationship_system_option{ :type => 'text/html', :'data-prefix' => 'system' }
  %li{ :'data-id' => '<%= system.id %>', :'data-title' => '<%= system.title %>', :'data-slug' => '<%= system.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= system.title %>
          %span.option <%= system.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_system_path('<%=system.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_process_option{ :type => 'text/html', :'data-prefix' => 'system' }
  %li{ :'data-id' => '<%= system.id %>', :'data-title' => '<%= system.title %>', :'data-slug' => '<%= system.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= system.title %>
          %span.option <%= system.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_system_path('<%=system.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_program_option{ :type => 'text/html', :'data-prefix' => 'program' }
  %li{ :'data-id' => '<%= program.id %>', :'data-title' => '<%= program.title %>', :'data-slug' => '<%= program.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= program.title %>
          %span.option <%= program.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_program_path('<%=program.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_directive_option{ :type => 'text/html', :'data-prefix' => 'directive' }
  %li{ :'data-id' => '<%= directive.id %>', :'data-title' => '<%= directive.title %>', :'data-slug' => '<%= directive.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= directive.title %>
          %span.option <%= directive.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_directive_path('<%=directive.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_product_option{ :type => 'text/html', :'data-prefix' => 'product' }
  %li{ :'data-id' => '<%= product.id %>', :'data-title' => '<%= product.title %>', :'data-slug' => '<%= product.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= product.title %>
          %span.option <%= product.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_product_path('<%=product.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_org_group_option{ :type => 'text/html', :'data-prefix' => 'org_group' }
  %li{ :'data-id' => '<%= org_group.id %>', :'data-title' => '<%= org_group.title %>', :'data-slug' => '<%= org_group.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= org_group.title %>
          %span.option <%= org_group.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_org_group_path('<%=org_group.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.btn.btn-mini.add-me{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_facility_option{ :type => 'text/html', :'data-prefix' => 'facility' }
  %li{ :'data-id' => '<%= facility.id %>', :'data-title' => '<%= facility.title %>', :'data-slug' => '<%= facility.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= facility.title %>
          %span.option <%= facility.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_facility_path('<%=facility.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_market_option{ :type => 'text/html', :'data-prefix' => 'market' }
  %li{ :'data-id' => '<%= market.id %>', :'data-title' => '<%= market.title %>', :'data-slug' => '<%= market.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= market.title %>
          %span.option <%= market.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_market_path('<%=market.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_data_asset_option{ :type => 'text/html', :'data-prefix' => 'data_asset' }
  %li{ :'data-id' => '<%= data_asset.id %>', :'data-title' => '<%= data_asset.title %>', :'data-slug' => '<%= data_asset.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= data_asset.title %>
          %span.option <%= data_asset.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_data_asset_path('<%=data_asset.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.btn.btn-mini.add-me{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_project_option{ :type => 'text/html', :'data-prefix' => 'project' }
  %li{ :'data-id' => '<%= project.id %>', :'data-title' => '<%= project.title %>', :'data-slug' => '<%= project.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= project.title %>
          %span.option <%= project.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_project_path('<%=project.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_risk_option{ :type => 'text/html', :'data-prefix' => 'risk' }
  %li{ :'data-id' => '<%= risk.id %>', :'data-title' => '<%= risk.title %>', :'data-slug' => '<%= risk.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= risk.title %>
          %span.option <%= risk.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_risk_path('<%=risk.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.add-me.btn.btn-mini{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right

%script#relationship_risky_attribute_option{ :type => 'text/html', :'data-prefix' => 'risky_attribute' }
  %li{ :'data-id' => '<%= risky_attribute.id %>', :'data-title' => '<%= risky_attribute.title %>', :'data-slug' => '<%= risky_attribute.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= risky_attribute.title %>
          %span.option <%= risky_attribute.slug %>
      .span4.actions
        .pull-right
          %a.widgetbtn.btn.btn-mini{:href => edit_flow_risky_attribute_path('<%=risky_attribute.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target' }
            %i.grcicon-edit
          %a.widgetbtn.btn.btn-mini.add-me{:href => "#", :'data-toggle' => 'selector-list-select'}
            %i.grcicon-chevron-right


.row-fluid.modal-source
  .span6
    .row-fluid
      .span7
        %h3
          =context[:source_title]
          %a.widgetbtn.widgetbtnselector.btn.btn-add{ :href => context[:option_new_url], :'data-toggle' => 'modal-ajax-listnewform', :'data-selector-target' => '.source, .target', :'data-modal-class' => 'modal-wide' }
            %i.grcicon-add
      .span5
        %input.widgetsearch.input-block-level{:type => "text", :placeholder => context[:source_search_text]}
    .filter-block
      .row-fluid
        .span12
          .tabbable.tabs-left
            .tab-content
              #category1.tab-pane.active
                .people-list
                  %ul.source{ :'data-list-data-href' => context[:options_url], :'data-template-id' => "relationship_#{context[:related_type].underscore}_option" }
  .span6
    %h3
      =context[:target_title]
    .people-list.currentlist
      %ul.target{ :'data-list-data-href' => context[:selected_url], :'data-template-id' => "relationship_selected" }

app/views/relationships/related_objects.json.erb
[
  <% @results.each_with_index do |result, result_index| %>
  {
    "relationship_type" : {
      "id" : <%= result[:relationship_type_id].to_json.html_safe %>,
      "title" : <%= result[:relationship_title].to_json.html_safe %>,
      "description" : <%= result[:relationship_description].to_json.html_safe %>,
      "related_type" : <%= result[:related_type].to_json.html_safe %>,
      "edit_url" : <%= result[:edit_url].to_json.html_safe %>
    },
    "related_objects" : [
      <% result[:objects].each_with_index do |obj, index| %>
        {
          "url" : <%= "#{obj.class.table_name}/#{obj.id}".to_json.html_safe %>,
          "object": {
            "type": <%= obj.class.to_s.to_json.html_safe %>,
            "id": <%= obj.id.to_json.html_safe %>,
            "slug" : <%= obj.slug.to_json.html_safe %>,
            "title" : <%= obj.title.to_json.html_safe %>
          }
        }
        <% if index != (result[:objects].count - 1)%>
        ,
        <% end %>
      <% end %>
    ]
  }
  <% if result_index != (@results.count - 1)%>
  ,
  <% end %>
  <% end %>
]