config/routes.rb
CmsRails::Application.routes.draw do

   get "signup" => "signup#index"
  post "signup" => "signup#signup"

  resources :programs, :as => 'flow_programs', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
      get 'sections'
      get 'controls'
    end
  end

  resources :directives, :as => 'flow_directives', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'export_controls'
      get 'export'
      get 'sections'
      get 'section_controls'
      get 'control_sections'
      get 'category_controls'
      get 'delete'
      get 'import_controls'
      post 'import_controls'
      get 'import'
      post 'import'
    end
  end

  resources :program_directives, :as => 'flow_program_directives', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :cycles, :as => 'flow_cycles', :only => [:show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :sections, :as => 'flow_sections', :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :controls, :as => 'flow_controls', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'sections'
      get 'implemented_controls'
      get 'implementing_controls'
      get 'systems'
      get 'risks'
      get 'delete'
    end
  end

  resources :systems, :as => 'flow_systems', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :system_systems, :as => 'flow_system_systems', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :system_controls, :as => 'flow_system_controls', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :transactions, :as => 'flow_transactions', :only => [:new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :products, :as => 'flow_products', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :org_groups, :as => 'flow_org_groups', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :facilities, :as => 'flow_facilities', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :markets, :as => 'flow_markets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :projects, :as => 'flow_projects', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :data_assets, :as => 'flow_data_assets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risky_attributes, :as => 'flow_risky_attributes', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risks, :as => 'flow_risks', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :control_risks, :as => 'flow_control_risks', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :risk_risky_attributes, :as => 'flow_risk_risky_attributes', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :accounts, :as => 'flow_accounts' do
    member do
      get 'delete'
    end
  end

  resources :people, :as => 'flow_people', :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :object_people, :as => 'flow_object_people', :only => [:index, :create, :update, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :documents, :as => 'flow_documents' do
    member do
      get 'delete'
    end
  end

  resources :object_documents, :as => 'flow_object_documents', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :categories, :as => 'flow_categories' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :options, :as => 'flow_options' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :categorizations, :as => 'flow_categorizations', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :relationships, :as => 'flow_relationships', :only => [:index, :create] do
    collection do
      get 'related_objects'
      get 'list_edit'
      get 'related'
      get 'graph'
    end
  end

  resources :pbc_lists, :as => 'flow_pbc_lists', :only => [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
      get 'import'
      post 'import'
      get 'export'
      get 'export_responses'
    end
  end

  resources :requests, :as => 'flow_requests', :only => [:new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :responses, :as => 'flow_responses', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :population_samples, :as => 'flow_population_samples', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :meetings, :as => 'flow_meetings', :only => [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :control_assessments, :as => 'flow_control_assessments', :only => [] do
    member do
      post 'rotate'
    end
  end

  match 'programs_dash' => 'programs_dash#index'
  match 'admin_dash' => 'admin_dash#index'

  get 'admin_dash/:action' => 'admin_dash'
  get 'design/templates/:name' => 'design#templates'
  get 'design/:action' => 'design'

  get "mapping/show/:program_id" => 'mapping#show', :as => 'mapping_program'
  get 'mapping_section_dialog/:section_id' => 'mapping#section_dialog', :as => 'mapping_section_dialog'
  post "mapping/map_rcontrol"
  post "mapping/map_ccontrol"
  put "mapping/update/:section_id" => 'mapping#update', :as => 'mapping_update'

  match 'help/:slug' => 'help#show', :as => :help
  post 'help' => 'help#edit', :as => :update_help

  if !Rails.env.test? && CmsRails::Application.sso_callback_url
    match 'sso/new' => 'sso#new', :as => 'login'
    match CmsRails::Application.sso_callback_url => "sso#callback"
    match 'sso/destroy' => 'sso#destroy', :as => 'logout'
  else
    match 'login' => 'user_sessions#login', :as => 'login'
    match 'user_sessions/destroy' => 'user_sessions#destroy', :as => 'logout'
    match 'user_sessions/create' => 'user_sessions#create'
  end

  match 'document/:action' => 'document'

  match 'evidence/index' => 'evidence#index'
  match 'evidence/show_closed_control/:system_id/:control_id' => 'evidence#show_closed_control'
  match 'evidence/show_control/:system_id/:control_id' => 'evidence#show_control'
  match 'evidence/new/:system_id/:control_id/:descriptor_id' => 'evidence#new'
  match 'evidence/new_gdoc/:system_id/:control_id/:descriptor_id' => 'evidence#new_gdoc'
  match 'evidence/attach/:system_id/:control_id/:descriptor_id' => 'evidence#attach'
  match 'evidence/show/:document_id' => 'evidence#show'
  match 'evidence/update/:document_id' => 'evidence#update'
  match 'evidence/destroy/:system_id/:control_id/:document_id' => 'evidence#destroy'
  match 'evidence/review/:document_id/:value' => 'evidence#review'

  root :to => "welcome#index"
  match 'about' => 'welcome#about', :as => 'about'
  match 'placeholder' => 'welcome#placeholder', :as => 'placeholder'
  match 'login_dispatch' => 'welcome#login_dispatch', :as => 'login_dispatch'
  get 'welcome/reload'

end

app/controllers/controls_controller.rb
# Author:: Miron Cuperman (mailto:miron+cms@google.com)
# Copyright:: FixNix Inc. 2012
# License:: Apache 2.0

# Handle Controls
class ControlsController < BaseObjectsController
  include ControlsHelper
  include AuthorizationHelper

  before_filter :load_control, :only => [:sections,
                                         :implemented_controls,
                                         :implementing_controls,
                                         :systems,
                                         :risks]

  cache_sweeper :control_sweeper, :only => [:create, :update, :destroy]

#  access_control :acl do
#    allow :superuser
#
#    actions :new, :create do
#      allow :create, :create_control
#    end
#
#    actions :edit, :update do
#      allow :update, :update_control, :of => :control
#    end
#
#    actions :show, :tooltip do
#      allow :read, :read_control, :of => :control
#    end
#
#    actions :index do
#      allow :read, :read_control
#    end
#
#    actions :sections, :implemented_controls, :implementing_controls do
#      allow :read, :read_control, :of => :control
#    end
#  end

  layout 'dashboard'

  def index
    @controls = Control
    if params[:s].present?
      @controls = @controls.fulltext_search(params[:s])
    end
    if params[:company].present?
      @controls = @controls.joins(:directive).where(Directive.arel_table[:company].eq(true))
    end
    if params[:directive_id].present?
      @controls = @controls.
        includes(:sections).
        where(
          Control.arel_table[:directive_id].eq(params[:directive_id]).or(
            Section.arel_table[:directive_id].eq(params[:directive_id])))
    end
    if params[:program_id].present?
      program = Program.where(:id => params[:program_id]).first
      directive_ids = program ? program.directive_ids : []
      @controls = @controls.
        includes(:sections).
        where(
          Control.arel_table[:directive_id].in(directive_ids).or(
            Section.arel_table[:directive_id].in(directive_ids)))
    end
    if params[:control_id].present?
      @controls = Control.find(params[:control_id]).implemented_controls
    end
    if params[:system_id].present?
      @controls = @controls.
        joins(:system_controls).
        where(:system_controls => { :system_id => params[:system_id] })
    end
    @controls = @controls.includes(:control_sections)
    @controls = allowed_objs(@controls.all, :read)

    if params[:list_select].present?
      render :partial => 'list_select', :layout => 'layouts/list_select_modal', :locals => {}
    elsif params[:quick]
      render :partial => 'quick', :locals => { :quick_result => params[:qr]}
    elsif params[:list].present?
      if params[:program_id].present?
        program = Program.where(:id => params[:program_id]).first
        if program.present? && program.company_controls?
          render :partial => 'list', :locals => { :controls => @controls, :include_linked_programs => true }
        else
          render :partial => 'list', :locals => { :controls => @controls }
        end
      else
        render :partial => 'list', :locals => { :controls => @controls }
      end
    elsif params[:category_tree].present?
      category_tree = Control.category_controls_tree(@controls)
      render :partial => 'category_tree', :locals => { :category_tree => category_tree }
    else
      if params[:ids_only].present?
        render :json => @controls, :only => [:id]
      else
        render :json => @controls, :methods => [:description_inline, :mapped_section_ids, :category_ids ]
      end
    end
  end

  def sections
    @sections = @control.sections.all
    # NOTE: removed non-directly-linked controls until control mapping is in
    #@sections =
    #  @control.sections.all +
    #  @control.implemented_controls.includes(:sections).map(&:sections).flatten
    @sections = allowed_objs(@sections, :read)
    @sections.sort_by(&:slug_split_for_sort)
    render :layout => nil, :locals => { :sections => @sections }
  end

  def implemented_controls
    @controls = @control.implemented_controls
    if params[:s].present?
      @controls = @controls.fulltext_search(params[:s])
    end
    @controls.all.sort_by(&:slug_split_for_sort)
    respond_to do |format|
      format.html do
        render :action => 'controls', :layout => nil, :locals => { :controls => @controls, :prefix => 'Parent of' }
      end
      format.json do
        render :json => @controls, :methods => :implemented_controls
      end
    end
  end

  def implementing_controls
    @controls = @control.implementing_controls
    if params[:s].present?
      @controls = @controls.fulltext_search(params[:s])
    end
    @controls.all.sort_by(&:slug_split_for_sort)
    render :action => 'controls', :layout => nil, :locals => { :controls => @controls, :prefix => 'Child of' }
  end

  def systems
    @systems = @control.systems
    if params[:s].present?
      @systems = @systems.fulltext_search(params[:s])
    end
    @systems = @systems.all

    render :action => 'systems', :layout => nil, :locals => { :systems => @systems, :control => @control }
  end

  def risks
    @risks = @control.risks
    if params[:s].present?
      @risks = @risks.fulltext_search(params[:s])
    end
    @risks = @risks.all

    render :action => 'risks', :layout => nil, :locals => { :risks => @risks, :control => @control }
  end

  private

    def create_object_as_json
      object.as_json :methods => [:description_inline, :mapped_section_ids, :category_ids ]
    end

    def update_object_as_json
      object.as_json :methods => [:description_inline, :mapped_section_ids, :category_ids ]
    end

    def load_control
      @control = Control.find(params[:id])
    end

    def delete_model_stats
      [ [ 'System Control', @control.system_controls.count ]
      ]
    end

    def extra_delete_relationship_stats
      [ [ 'Section', @control.control_sections.count ],
        [ 'Implemented Control', @control.implemented_controls.count ],
        [ 'Implementing Control', @control.implementing_controls.count ],
      ]
    end

    def post_destroy_path
      flow_directive_path(@control.directive)
    end
end

app/helpers/controls_helper.rb
module ControlsHelper
  def control_params
    control_params = params[:control] || {}
    if control_params[:directive_id]
      # TODO: Validate the user has access to add controls to the directive
      control_params[:directive] = Directive.where(:id => control_params.delete(:directive_id)).first
    end
    %w(type kind means verify_frequency).each do |field|
      parse_option_param(control_params, field)
    end
    %w(start_date stop_date).each do |field|
      parse_date_param(control_params, field)
    end
    %w(category assertion).each do |field|
      value_ids = control_params.delete(field + '_ids')
      values = []
      if value_ids.respond_to?(:each)
        value_ids.each do |value_id|
          values.push(Category.where(:id => value_id).first)
        end
        control_params[field.pluralize] = values
      end
    end
    control_params
  end
end

app/views/controls/_category_branch.haml
-# Requires category, children, controls

-subcategory_content_id = "content_#{rand(36**8).to_s(36)}"

%li{ :class => 'category', :'data-object-id' => category ? category.id : nil, :'data-object-type' => 'category' }
  -#%h3=category ? category.name : 'Uncategorized Controls'
  .item-main
    .openclose.active
    .item-title
      .row-fluid
        =category ? category.name : 'Uncategorized Controls'
  .item-content.in
    -if controls && controls.size > 0
      %ul.tree-structure
        -controls.each do |control|
          -sections = control.linked_sections
          %li
            .item-main
              .openclose{ :class => 'lastchild' }
              .item-title
                .row-fluid
                  -if sections.size > 0
                    =render :partial => 'object_leaf', :locals => { :instance => control, :object_icon => (sections.size > 0 ? 'grcicon-control-color' : 'grcicon-control-danger') }
                  -else
                    =render :partial => 'object_leaf', :locals => { :instance => control, :object_icon => (sections.size > 0 ? 'grcicon-control-color' : 'grcicon-control-danger'), :title => "<span class='not-mapped'>NOT MAPPED</span> #{h control.title}".html_safe }
                  .span2
                    .objects-count
                      -popover_content = capture_haml do
                        -if !sections.empty?
                          %ul.tree-structure.simple
                            -sections.each do |section|
                              %li.control
                                .item-main
                                  .item-title
                                    .row-fluid
                                      .span12
                                        .oneline
                                          =section.slug
                                          &mdash;
                                          =section.title
                        -else
                          .rtf
                            %p.no-data
                              No sections are linked to this control

                      -data_popover_trigger = { :placement => "right",
                                           :'popover-trigger' =>  "sticky-hover",
                                           :'original-title' => "<div class='row-fluid'><div class='span12'><h3><i class='#{sections.size > 0 ? 'grcicon-section-color' : 'grcicon-section-danger'}'></i>Linked Sections</h3></div></div>".html_safe,
                                           :content => popover_content }
                      %a.controls-count{ :href => "javascript://", :data => data_popover_trigger }
                        %i{ :class => (sections.size > 0 ? 'grcicon-section-color' : 'grcicon-section-danger') }
                        =sections.size
                .item-actions
                  %a.btn.btn-mini.pull-right{ :href => flow_control_path(control), :title => 'View Control' }
                    %i.grcicon-goto
    -if children && children.size > 0
      %ul.tree-structure
        -children.each do |subcategory, subchildren, subcontrols|
          =render :partial => 'category_branch',
                  :locals => { :category => subcategory, :children => subchildren, :controls => subcontrols }

app/views/controls/_category_tree.haml
%ul.tree-structure
  -category_tree.each do |category, children, controls|
    =render :partial => 'category_branch',
            :locals => { :category => category, :children => children, :controls => controls }

app/views/controls/_list.haml
-include_linked_programs = false if local_assigns[:include_linked_programs].nil?

%ul.tree-structure.control
  =walk_slug_tree(Directive.slugtree(controls), :li_class => 'control') do |item, step|
    -content_id = "content_#{rand(36**8).to_s(36)}" # unique ID for toggle

    .item-main
      .openclose{ :class => 'lastchild' }
      .item-title
        .row-fluid
          =render :partial => 'object_leaf', :locals => { :instance => item }

          -if include_linked_programs
            -programs = item.linked_programs.uniq
            .span2
              .objects-count
                -popover_content = capture_haml do
                  -if !programs.empty?
                    %ul.tree-structure.simple
                      -programs.each do |program|
                        %li.program
                          .item-main
                            .item-title
                              .row-fluid
                                .span12
                                  .oneline
                                    %a{ :href => flow_program_path(program) }=program.title
                  -else
                    .rtf
                      %p.no-data
                        No programs are linked to this company control
                -data_popover_trigger = { :placement => "right",
                                     :'popover-trigger' =>  "sticky-hover",
                                     :'original-title' => "<i class='grcicon-program-color'></i> Programs using #{item.slug}".html_safe,
                                     :content => popover_content }
                %a{ :data => data_popover_trigger }
                  %i.grcicon-program-color
                  =programs.size #not using count because count kicks off another query that returns an incorrect result
        .item-actions
          %a.btn.btn-mini.pull-right{ :href => flow_control_path(item), :rel => 'tooltip', :title => "Go to this object's page" }
            %i.grcicon-goto
          %a.btn.btn-mini.pull-right{ :href => edit_flow_control_path(item), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-dirty' => "#controls, #combo", :rel => 'tooltip', :title => 'Edit Control' }
            %i.grcicon-edit

app/views/controls/_list_select.haml
-content_for :modal_title do
  Select Control

-content_for :modal_help, :select_control

%script#control_option{ :type => 'text/html', :'data-prefix' => 'control' }
  %li{ :'data-id' => '<%= control.id %>', :'data-title' => '<%= control.title %>', :'data-slug' => '<%= control.slug %>' }
    .row-fluid
      .span8
        .object-info
          %span.name <%= control.title %>
          %span.option <%= control.slug %>
      .span4.actions
        -#%a.widgetbtn.pull-right{:href => edit_flow_control_path('<%=control.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source', :'data-modal-class' => 'modal-wide' }
          %i.grcicon-edit

%script#control_option_data{ :type => 'text/html' }
  .object-info
    %span.name <%= control.title %>
    %span.option <%= control.slug %>

.row-fluid.modal-source
  .span12
    %h3
      Select Control
      %a.widgetbtn.widgetbtnselector.btn.btn-add{ :href => new_flow_control_path, :'data-toggle' => 'modal-ajax-listnewform', :'data-selector-target' => '.source', :'data-modal-class' => 'modal-wide' }
        %i.grcicon-add
      .pull-right
        %input.widgetsearch{:type => "text", :placeholder => "Search Controls"}

    .filter-block
      .row-fluid
        .span12
          .tabbable.tabs-left
            .tab-content
              #category1.tab-pane.active
                .people-list
                  %ul.source{ :'data-list-data-href' => flow_controls_path(:format => :json), :'data-template-id' => 'control_option' }

app/views/controls/_main.haml
-content_for :widget_title do
  Control Implementation

-content_for :widget_help, 'control_main'

-content_for :widget_id, 'control_main_widget'

.tabbable
  %ul.nav.nav-tabs
    %li.text-business=link_to '<i class="grcicon-system-color"></i>Systems / <i class="grcicon-process-color"></i>Processes'.html_safe, '#systems_processes', :data => { :toggle => 'tab', :'tab-href' => systems_flow_control_path(control) }
    -if control.directive.company?
      %li.text-governance=link_to '<i class="grcicon-control-color"></i>Mapped Controls'.html_safe, '#controls', :data => { :toggle => 'tab', :'tab-href' => implemented_controls_flow_control_path(control) }
    -else
      %li.text-governance=link_to '<i class="grcicon-control-color"></i>Mapped Controls'.html_safe, '#controls', :data => { :toggle => 'tab', :'tab-href' => implementing_controls_flow_control_path(control) }
    %li.text-governance=link_to '<i class="grcicon-section-color"></i>Sections/Clauses'.html_safe, '#sections', :data => { :toggle => 'tab', :'tab-href' => sections_flow_control_path(control) }
    - if current_user.can_manage_risk?
      %li.text-risk=link_to '<i class="grcicon-risk-color"></i>Risks'.html_safe, '#risks', :data => { :toggle => 'tab', :'tab-href' => risks_flow_control_path(control) }

  .action-items
    %a.expandAll.btn.btn-mini{:href => "#", :rel => "tooltip", :title => "Expand all"}
      %i.grcicon-wide-black
    %a.shrinkAll.btn.btn-mini{:href => "#", :rel => "tooltip", :title => "Collapse all"}
      %i.grcicon-normal-black

  .tab-content
    #systems_processes.tab-pane
    #controls.tab-pane
    #sections.tab-pane
    #risks.tab-pane

app/views/controls/_mappings.haml
-content_for :widget_title do
  Regulations and Controls

-content_for :widget_help, 'control_mappings'

-content_for :widget_id, 'control_mappings_widget'

-content_for :widget_buttons do
  %a.widgettextbtn{ :href => new_flow_section_path(:'section[directive_id]' => control.directive_id), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'refresh', :title => 'Create New Section/ Clause' } Add Section / Clause
  %a.widgettextbtn{ :href => new_flow_control_path(:'control[directive_id]' => control.directive_id), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'refresh', :'data-modal-class' => 'modal-wide', :title => 'Create New Control' } Add Control

.tabbable
  %ul.nav.nav-tabs
    %li=link_to 'Sections / Clauses', '#regulations', :data => { :toggle => 'tab', :'tab-href' => sections_flow_control_path(control) }
    -if control.directive.company?
      %li=link_to 'Controls', '#controls', :data => { :toggle => 'tab' }
    -else
      %li=link_to 'Controls', '#controls', :data => { :toggle => 'tab' }
  .tab-content.tab-position
    #regulations.tab-pane
    #controls.tab-pane

app/views/controls/_text.haml
-content_for :widget_title do
  Control Text

-content_for :widget_help, 'control_text'

-content_for :widget_id, 'control_text_widget'

.row-fluid
  .span12.well
    =display_as_html control.description

app/views/controls/controls.haml
-# locals: controls, prefix

%h3.tab-title
  Other controls linked to this control

%ul.tree-structure
  =walk_slug_tree(Directive.slugtree(controls), :li_class => 'control') do |item, step|
    -content_id = "content_#{rand(36**8).to_s(36)}" # unique ID for toggle
    .item-main
      .openclose{ :class => 'lastchild' }
      .item-title
        .row-fluid
          =render :partial => 'object_leaf', :locals => { :instance => item }
        .item-actions
          %a.btn.btn-mini.halfopacity{ "rel" => "tooltip", "data-placement" => "left", "title" => "Go to this object's page", :href => flow_control_path(item.id) }
            %i.grcicon-arrowright-black

app/views/controls/index.haml
-content_for :header do
  %ul.breadcrumbs
    %li=link_to "dashboard", programs_dash_path
  %h1
    Controls

.box
  .head
    %h1 Controls
  .body
    %ul
      -@controls.each do |control|
        %li.item
          =link_to control.slug, flow_control_path(control)
          

app/views/controls/sections.haml
-# locals: sections

%h3.tab-title
  Sections / Clauses that mandate this Control

%ul.tree-structure
  =walk_slug_tree(Directive.slugtree(sections), :li_class => 'section') do |item, step|
    -content_id = "content_#{rand(36**8).to_s(36)}" # unique ID for toggle
    .item-main
      .openclose{ :class => 'lastchild' }
      .item-title
        .row-fluid
          =render :partial => 'object_leaf', :locals => { :instance => item }
        .item-actions

app/views/controls/show.haml
-@title = "GRC Control: #{@control.title}"

-content_for :header do
  %ul.breadcrumbs
    %li=link_to "dashboard", programs_dash_path
    %li=@control.slug
  
  %h1.governance
    .grcobject.governance{:rel => "tooltip", :'data-placement'=>"bottom", :title => "Control"}
      %i.grcicon-control
    -if @control.title?
      =strip_tags(@control.title)
    -else
      =@control.slug


-content_for :page_help, 'control'

-content_for :subheader_extras do
  %ul.actions.pull-right
    %li
      %a{ :href => edit_flow_control_path(@control), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'refresh', :'data-modal-class' => 'modal-wide', :title => 'Edit Control' }
        %i.grcicon-edit
        %span Edit Control

-content_for :subheader_plus do
  %a.navbarplus.fltrt{ :href => new_flow_control_path('control[directive_id]' => @control.directive_id), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'redirect', :'data-modal-class' => 'modal-wide' }

.container-fluid
  #controls_columns.row-fluid{ :'data-resize' => "true" }
    #main_column.span8.widget-area
      =render :partial => 'controls/main',
              :layout => 'layouts/widget_box',
              :locals => { :control => @control, :widget_class => "governance widget-tabs widget-tabs-horizontal" }
      =render :partial => 'shared/add_widget_section'
    #right_column.span4.widget-area
      =render :partial => 'controls/info',
              :layout => 'layouts/widget_box',
              :locals => { :control => @control, :widget_class => "governance" }
      =render :partial => 'controls/more_info',
              :layout => 'layouts/widget_box',
              :locals => { :control => @control, :widget_class => 'related business' }
      =render :partial => 'shared/add_widget_section'