config/routes.rb
CmsRails::Application.routes.draw do

   get "signup" => "signup#index"
  post "signup" => "signup#signup"

  resources :programs, :as => 'flow_programs', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
      get 'sections'
      get 'controls'
    end
  end

  resources :directives, :as => 'flow_directives', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'export_controls'
      get 'export'
      get 'sections'
      get 'section_controls'
      get 'control_sections'
      get 'category_controls'
      get 'delete'
      get 'import_controls'
      post 'import_controls'
      get 'import'
      post 'import'
    end
  end

  resources :program_directives, :as => 'flow_program_directives', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :cycles, :as => 'flow_cycles', :only => [:show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :sections, :as => 'flow_sections', :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :controls, :as => 'flow_controls', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'sections'
      get 'implemented_controls'
      get 'implementing_controls'
      get 'systems'
      get 'risks'
      get 'delete'
    end
  end

  resources :systems, :as => 'flow_systems', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :system_systems, :as => 'flow_system_systems', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :system_controls, :as => 'flow_system_controls', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :transactions, :as => 'flow_transactions', :only => [:new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :products, :as => 'flow_products', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :org_groups, :as => 'flow_org_groups', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :facilities, :as => 'flow_facilities', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :markets, :as => 'flow_markets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :projects, :as => 'flow_projects', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :data_assets, :as => 'flow_data_assets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risky_attributes, :as => 'flow_risky_attributes', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risks, :as => 'flow_risks', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :control_risks, :as => 'flow_control_risks', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :risk_risky_attributes, :as => 'flow_risk_risky_attributes', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :accounts, :as => 'flow_accounts' do
    member do
      get 'delete'
    end
  end

  resources :people, :as => 'flow_people', :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :object_people, :as => 'flow_object_people', :only => [:index, :create, :update, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :documents, :as => 'flow_documents' do
    member do
      get 'delete'
    end
  end

  resources :object_documents, :as => 'flow_object_documents', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :categories, :as => 'flow_categories' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :options, :as => 'flow_options' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :categorizations, :as => 'flow_categorizations', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :relationships, :as => 'flow_relationships', :only => [:index, :create] do
    collection do
      get 'related_objects'
      get 'list_edit'
      get 'related'
      get 'graph'
    end
  end

  resources :pbc_lists, :as => 'flow_pbc_lists', :only => [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
      get 'import'
      post 'import'
      get 'export'
      get 'export_responses'
    end
  end

  resources :requests, :as => 'flow_requests', :only => [:new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :responses, :as => 'flow_responses', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :population_samples, :as => 'flow_population_samples', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :meetings, :as => 'flow_meetings', :only => [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :control_assessments, :as => 'flow_control_assessments', :only => [] do
    member do
      post 'rotate'
    end
  end

  match 'programs_dash' => 'programs_dash#index'
  match 'admin_dash' => 'admin_dash#index'

  get 'admin_dash/:action' => 'admin_dash'
  get 'design/templates/:name' => 'design#templates'
  get 'design/:action' => 'design'

  get "mapping/show/:program_id" => 'mapping#show', :as => 'mapping_program'
  get 'mapping_section_dialog/:section_id' => 'mapping#section_dialog', :as => 'mapping_section_dialog'
  post "mapping/map_rcontrol"
  post "mapping/map_ccontrol"
  put "mapping/update/:section_id" => 'mapping#update', :as => 'mapping_update'

  match 'help/:slug' => 'help#show', :as => :help
  post 'help' => 'help#edit', :as => :update_help

  if !Rails.env.test? && CmsRails::Application.sso_callback_url
    match 'sso/new' => 'sso#new', :as => 'login'
    match CmsRails::Application.sso_callback_url => "sso#callback"
    match 'sso/destroy' => 'sso#destroy', :as => 'logout'
  else
    match 'login' => 'user_sessions#login', :as => 'login'
    match 'user_sessions/destroy' => 'user_sessions#destroy', :as => 'logout'
    match 'user_sessions/create' => 'user_sessions#create'
  end

  match 'document/:action' => 'document'

  match 'evidence/index' => 'evidence#index'
  match 'evidence/show_closed_control/:system_id/:control_id' => 'evidence#show_closed_control'
  match 'evidence/show_control/:system_id/:control_id' => 'evidence#show_control'
  match 'evidence/new/:system_id/:control_id/:descriptor_id' => 'evidence#new'
  match 'evidence/new_gdoc/:system_id/:control_id/:descriptor_id' => 'evidence#new_gdoc'
  match 'evidence/attach/:system_id/:control_id/:descriptor_id' => 'evidence#attach'
  match 'evidence/show/:document_id' => 'evidence#show'
  match 'evidence/update/:document_id' => 'evidence#update'
  match 'evidence/destroy/:system_id/:control_id/:document_id' => 'evidence#destroy'
  match 'evidence/review/:document_id/:value' => 'evidence#review'

  root :to => "welcome#index"
  match 'about' => 'welcome#about', :as => 'about'
  match 'placeholder' => 'welcome#placeholder', :as => 'placeholder'
  match 'login_dispatch' => 'welcome#login_dispatch', :as => 'login_dispatch'
  get 'welcome/reload'

end

app/models/document.rb
# A Document
#
# Can either be linked by a URL or attached from Google Docs.
class Document < ActiveRecord::Base
  include AuthoredModel
  include AuthorizedModel
  include RelatedModel
  include SanitizableAttributes

  VALID_SCHEMES = ['http', 'https', 'file']

  attr_accessible :link, :title, :description, :type, :kind, :language, :year

  has_many :object_documents, :dependent => :destroy
  has_many :population_worksheets_documented, :class_name => "PopulationSample", :dependent => :nullify, :foreign_key => "population_document_id"
  has_many :sample_worksheets_documented, :class_name => "PopulationSample", :dependent => :nullify, :foreign_key => "sample_worksheet_document_id"
  has_many :sample_evidences_documented, :class_name => "PopulationSample", :dependent => :nullify, :foreign_key => "sample_evidence_document_id"

  belongs_to :type, :class_name => 'Option', :conditions => { :role => 'document_type' }
  belongs_to :kind, :class_name => 'Option', :conditions => { :role => 'reference_type' }
  belongs_to :year, :class_name => 'Option', :conditions => { :role => 'document_year' }
  belongs_to :language, :class_name => 'Option', :conditions => { :role => 'language' }

  is_versioned_ext

  sanitize_attributes :description

  validate :link do
    begin
      if link.nil? || VALID_SCHEMES.include?(link.scheme)
        true
      else
        errors.add(:link, "scheme must be one of #{VALID_SCHEMES.join(', ')}")
      end
    rescue
      errors.add(:link, "must be a valid URI")
    end
  end

  validates :link,
    :presence => { :message => "needs a value" },
    :uniqueness => true

  def display_name
    title
  end

  def link
    link = read_attribute(:link)
    URI(link) if !link.blank?
  rescue
    link
  end

  def self.linkify(value)
    if !value.blank?
      if !VALID_SCHEMES.include?(value.split(':')[0])
        value = "http://#{value}"
      else
        value
      end
    end
  end

  def link=(value)
    if !value.blank? && !VALID_SCHEMES.include?(value.split(':')[0])
      value = "http://#{value}"
    end
    write_attribute(:link, value)
  end

  def link_url
    link && link.to_s
  end

  def document_type
    type && type.title
  end

  def complete?
    !link.nil? && !link.to_s.blank?
  end
  
  def count_population_samples
    t = PopulationSample.arel_table
    is_population_document = t[:population_document_id].eq(id)
    is_sample_worksheet_document = t[:sample_worksheet_document_id].eq(id)
    is_sample_evidence_document = t[:sample_evidence_document_id].eq(id)
    PopulationSample.where(
      is_population_document.or(is_sample_worksheet_document).or(is_sample_evidence_document)
    ).count
  end

  def self.db_search(q)
    q = "%#{q}%"
    t = arel_table
    where(t[:title].matches(q).
      or(t[:link].matches(q)))
  end
end

app/controllers/document_controller.rb
# Author:: Miron Cuperman (mailto:miron+cms@google.com)
# Copyright:: FixNix Inc. 2011
# License:: Apache 2.0

# Handle Google Docs integration

class DocumentController < ApplicationController
  include GdataHelper
  include DocumentHelper

#  access_control :acl do
#    allow :superuser
#
#    actions :index do
#      allow :read, :read_document
#    end
#
#    actions :sync do
#      allow :update, :update_document
#    end
#  end

  before_filter :need_cycle

  # Show the list of Google docs
  def index
    return unless auth_gdocs
    @folders = get_gfolders()
    return if !@folders
    render 'document/index'
  end

  # Sync our local list of document folders with Google Docs.
  #
  # Ensure that folders exist for CMS/CYCLE, CMS/CYCLE/Systems, Cms/CYCLE/Accepted and each system.
  def sync
    folders = get_gfolders(:refresh => true)
    folders or return

    by_title = gdocs_by_title(folders)

    @messages = []

    top = by_title['CMS']
    unless top
      flash[:error] = 'No CMS folder in your Google Docs'
      return render 'document/sync'
    end

    client = get_gdata_client
    return unless client

    unless by_title[cycle_gfolder(@cycle)]
      folder = client.create_folder(@cycle.slug, :parent => top)
      by_title[cycle_gfolder(@cycle)] = folder
      session[:gfolders] = {} # clear cache
      @messages << "Created #{folder.full_title}"
    end

    cycle_folder = by_title["#{top.full_title}/#{@cycle.slug}"]

    ['Systems', 'Accepted'].each do |name|
      unless by_title["#{cycle_folder.full_title}/#{name}"]
        folder = client.create_folder(name, :parent => cycle_folder)
        by_title["#{cycle_folder.full_title}/#{name}"] = folder
        session[:gfolders] = {} # clear cache
        @messages << "Created #{folder.full_title}"
      end
    end

    systems = by_title["#{cycle_folder.full_title}/Systems"]

    System.all.each do |sys|
      path = system_gfolder(@cycle, sys)
      unless by_title[path]
        folder = client.create_folder(sys.slug, :parent => systems)
        session[:gfolders] = {} # clear cache
        @messages << "Created #{folder.full_title}"
      end
    end
  end
end

app/controllers/documents_controller.rb
# Author:: Miron Cuperman (mailto:miron+cms@google.com)
# Copyright:: FixNix Inc. 2012
# License:: Apache 2.0

# Handle Documents
class DocumentsController < BaseObjectsController

#  access_control :acl do
#    allow :superuser
#
#    actions :create, :new do
#      allow :create, :create_document
#    end
#
#    actions :show do
#      allow :read, :read_document, :of => :document
#    end
#
#    actions :index do
#      allow :read, :read_document
#    end
#
#    actions :edit, :update do
#      allow :update, :update_document, :of => :document
#    end
#
#    actions :destroy do
#      allow :destroy, :delete_document, :of => :document
#    end
#  end

  layout 'dashboard'

  no_base_action :tooltip

  def index
    @documents = Document
    if params[:s].present?
      @documents = @documents.db_search(params[:s])
    end
    @documents = allowed_objs(@documents.all, :read)
    if params[:list_select].present?
      render :partial => 'list_select', :layout => 'layouts/list_select_modal', :locals => {}
    else
      render :json => @documents, :methods => [:document_type, :link_url]
    end
  end

  private

    def object_as_json(args=nil)
      super(:methods => [:descriptor, :link_url])
    end

    def extra_delete_relationship_stats
        ObjectDocument.where(:document_id => @document.id).all.map do |od|
          documentation_type = od.documentable_type == 'Response' ? 'Documentation Response' : od.documentable_type
          #documentation_type = documentation_type == 'Document' ? 'Document Reference' : documentation_type
          [documentation_type, od.documentable]
        end +
      [
        ['Population Sample Response', @document.count_population_samples]
      ] 
    end

    def document_params
      document_params = params[:document] || {}
      %w(type kind year language).each do |field|
        parse_option_param(document_params, field)
      end
      document_params
    end
end

app/helpers/document_helper.rb
# Helper methods defined here can be accessed in any controller or view in the application

module DocumentHelper
  # Transform a document URL for display purposes.
  #
  # Currently just transforms a Google Docs url to the editable document
  # version.
  def transform_document_url(url)
    gdoc_url = Gdoc.edit_url_from_id_url(url)
    return gdoc_url if gdoc_url
    return url
  end
end

app/views/documents/_form.haml
-content_for :modal_title do
  -if f.object.new_record?
    Create a new reference
  -else
    Edit reference

-if !f.object.new_record? && params[:no_delete].nil?
  -content_for :modal_delete_path, delete_flow_document_path(f.object)

.row-fluid
  .span4
    .span12{ :class => error_class(f, :title) }
      =f.label :title, "Title".html_safe
      =f.text_field :title, :class => 'span12', :placeholder => 'Enter the title of this reference'
      =error_messages_inline(f, :title)

  =wrapped_select(f, :span2, :year_id, Option.options_for(:document_year).ordered_by_title_desc.map { |o| [o.title, o.id] }, :selected => (f.object.respond_to?(:year_id) ? f.object.year_id : nil), :include_blank => true)
  =wrapped_select(f, :span2, :language_id, Option.options_for(:language).map { |o| [o.title, o.id] }, :selected => (f.object.respond_to?(:language_id) ? f.object.language_id : nil), :include_blank => true)
  =wrapped_select(f, :span2, :kind_id, Option.options_for(:reference_type).map { |o| [o.title, o.id] }, :selected => (f.object.respond_to?(:kind_id) ? f.object.kind_id : nil), :include_blank => true, :label_name => 'Reference Kind')
  =wrapped_select(f, :span2, :type_id, Option.options_for(:document_type).map { |o| [o.title, o.id] }, :selected => (f.object.respond_to?(:type_id) ? f.object.type_id : nil), :include_blank => true, :label_name => 'DocType')

%br

.row-fluid
  =wrapped_text_area f, :span12, :description, :class => 'double wysihtml5', :wrapper_div_class => 'wysiwyg-area', :placeholder => 'Enter description here'

.row-fluid
  .span12{ :class => error_class(f, :link) }
    =f.label :link, "URL <span class='required'>*</span>".html_safe
    =f.text_field :link, :class => 'span12', :placeholder => 'https://www.example.com/xyz.pdf'
    =error_messages_inline(f, :link)

%br

=render :partial => "shared/wysihtml5"

app/views/documents/_list_select.haml
-content_for :modal_title do
  %h1 Select References

-content_for :modal_help, :select_reference

%script#document_option{ :type => 'text/html', :'data-prefix' => 'document' }
  %li{ :'data-id' => '<%= document.id %>', :'data-title' => '<%= document.title %>', :'data-document_type' => '<%= document.document_type %>' }
    .row-fluid
      .span6.object_info{ :'data-template-id' => 'document_option_data' }
      .span6.actions
        %a.widgetbtn.pull-right{ :href => edit_flow_document_path('<%=document.id%>'), :'data-toggle' => 'modal-ajax-listeditform', :'data-selector-target' => '.source, .target', :'data-modal-class' => 'modal-wide' }
          %i.grcicon-edit

%script#document_option_data{ :type => 'text/html' }
  %span.company <%= document.document_type || '&nbsp;' %>
  %span.name <%= document.title %>

.row-fluid
  .span12
    %h4
      Select Reference
      %a.widgetbtn.widgetbtnselector{ :href => new_flow_document_path, :'data-toggle' => 'modal-ajax-listnewform', :'data-selector-target' => '.source' }
        %i.grcicon-add
      .pull-right
        %input.widgetsearch{:type => "text", :placeholder => "Search References"}

    .filter-block
      .row-fluid
        .span12
          .tabbable.tabs-left
            .tab-content
              #category1.tab-pane.active
                .people-list.documents-list
                  %ul.source{ :'data-list-data-href' => flow_documents_path, :'data-template-id' => 'document_option' }

app/views/documents/_object_list.haml
-# locals: object
-all_object_documents = object.object_documents.all

%li.tab-title-holder
  .item-main
    .item-title
      .row-fluid
        .span12
          .js-list-container-title
            %h3.tab-title
              References
              %span{:class => "grc-badge #{all_object_documents.count.zero? ? "no-object" : ""}"}
                (#{all_object_documents.count})
              %a.pull-right{:href => list_edit_flow_object_documents_path(:object_type => object.class.name, :object_id => object.id), :'data-toggle' => 'modal-ajax-relationship-selector', :'data-modal-reset' => 'reset', :'data-list-target' => '#referenceList', :'data-modal-class' => 'modal-wide', :rel => "tooltip", :'data-placement'=> "left", :title => "Link References"}
                %i.grcicon-link


  %script#reference_list_item{ :type => 'text/html', :'data-member' => 'object_document'}
    %li.controlSlot{ :'data-id' => '<%= document.id %>' }
      <% if (document.link_url && document.link_url.length > 0) { %>
      .item-main
        .item-title
          .row-fluid
            .span12
              .oneline
                %span.addition-info
                  %a.reference{:href => '<%= document.link_url %>', :target => "_blank"}
                    <%= document.title || document.link_url || '&nbsp;' %>
                %span.option
                  <%= document.document_type || '&nbsp;' %>
      
      <% } else { %>
      .item-main
        .item-title
          .row-fluid
            .span12
              .oneline
                %span.addition-info
                  <%= document.title || document.link_url || '&nbsp;' %>
                %span.option
                  <%= document.document_type || '&nbsp;' %>
      <% } %>
  
  %ul#referenceList.tree-structure{ :'data-template-id' => 'reference_list_item' }
    -all_object_documents.each do |object_item|
      -item = object_item.document
      %li{ :'data-id' => item.id }
        -if item.link_url.present?
          .item-main
            .item-title
              .row-fluid
                .span12
                  .oneline
                    %span.addition-info
                      %a.reference{:href => item.link_url,
                        :target => "_blank",
                        :data => { :'popover-trigger' => "sticky-hover", 
                                   :'original-title' => "<div class='row-fluid'><div class='span12'><h3><i class='grcicon-link'></i> Viewing #{item.title.blank? ? item.link_url : item.title} </span> </h3></div></div>", 
                                   :content => render(:partial => 'documents/tooltip', :locals => { :document => item }) } }
                        =item.title.presence || item.link_url || ''.html_safe
                    %span.option
                      =item.document_type || ''.html_safe
                  
        -else
          .item-main
            .item-title
              .row-fluid
                .span12
                  .oneline
                    %span.addition-info
                      =item.title.presence || item.link_url || ';'.html_safe
                    %span.option
                      =item.document_type || ''.html_safe
                
  

app/views/documents/_tooltip.haml
.preview-container
  %iframe.preview{ :src => document.link_url}