config/routes.rb
CmsRails::Application.routes.draw do

   get "signup" => "signup#index"
  post "signup" => "signup#signup"

  resources :programs, :as => 'flow_programs', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
      get 'sections'
      get 'controls'
    end
  end

  resources :directives, :as => 'flow_directives', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'export_controls'
      get 'export'
      get 'sections'
      get 'section_controls'
      get 'control_sections'
      get 'category_controls'
      get 'delete'
      get 'import_controls'
      post 'import_controls'
      get 'import'
      post 'import'
    end
  end

  resources :program_directives, :as => 'flow_program_directives', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :cycles, :as => 'flow_cycles', :only => [:show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :sections, :as => 'flow_sections', :only => [:index, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
  end

  resources :controls, :as => 'flow_controls', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'sections'
      get 'implemented_controls'
      get 'implementing_controls'
      get 'systems'
      get 'risks'
      get 'delete'
    end
  end

  resources :systems, :as => 'flow_systems', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :system_systems, :as => 'flow_system_systems', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :system_controls, :as => 'flow_system_controls', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :transactions, :as => 'flow_transactions', :only => [:new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :products, :as => 'flow_products', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :org_groups, :as => 'flow_org_groups', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :facilities, :as => 'flow_facilities', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :markets, :as => 'flow_markets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :projects, :as => 'flow_projects', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :data_assets, :as => 'flow_data_assets', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risky_attributes, :as => 'flow_risky_attributes', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
  end

  resources :risks, :as => 'flow_risks', :only => [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      get 'delete'
      get 'tooltip'
      get 'delete'
    end
    collection do
      get 'import'
      post 'import'
      get 'export'
    end
  end

  resources :control_risks, :as => 'flow_control_risks', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :risk_risky_attributes, :as => 'flow_risk_risky_attributes', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :accounts, :as => 'flow_accounts' do
    member do
      get 'delete'
    end
  end

  resources :people, :as => 'flow_people', :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :object_people, :as => 'flow_object_people', :only => [:index, :create, :update, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :documents, :as => 'flow_documents' do
    member do
      get 'delete'
    end
  end

  resources :object_documents, :as => 'flow_object_documents', :only => [:index, :create, :destroy] do
    collection do
      get 'list_edit'
    end
  end

  resources :categories, :as => 'flow_categories' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :options, :as => 'flow_options' do
    member do
      get 'delete'
    end
    collection do
      get 'export'
    end
  end

  resources :categorizations, :as => 'flow_categorizations', :only => [:index, :create] do
    collection do
      get 'list_edit'
    end
  end

  resources :relationships, :as => 'flow_relationships', :only => [:index, :create] do
    collection do
      get 'related_objects'
      get 'list_edit'
      get 'related'
      get 'graph'
    end
  end

  resources :pbc_lists, :as => 'flow_pbc_lists', :only => [:show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
      get 'import'
      post 'import'
      get 'export'
      get 'export_responses'
    end
  end

  resources :requests, :as => 'flow_requests', :only => [:new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :responses, :as => 'flow_responses', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :population_samples, :as => 'flow_population_samples', :only => [:index, :create, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :meetings, :as => 'flow_meetings', :only => [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get 'delete'
    end
  end

  resources :control_assessments, :as => 'flow_control_assessments', :only => [] do
    member do
      post 'rotate'
    end
  end

  match 'programs_dash' => 'programs_dash#index'
  match 'admin_dash' => 'admin_dash#index'

  get 'admin_dash/:action' => 'admin_dash'
  get 'design/templates/:name' => 'design#templates'
  get 'design/:action' => 'design'

  get "mapping/show/:program_id" => 'mapping#show', :as => 'mapping_program'
  get 'mapping_section_dialog/:section_id' => 'mapping#section_dialog', :as => 'mapping_section_dialog'
  post "mapping/map_rcontrol"
  post "mapping/map_ccontrol"
  put "mapping/update/:section_id" => 'mapping#update', :as => 'mapping_update'

  match 'help/:slug' => 'help#show', :as => :help
  post 'help' => 'help#edit', :as => :update_help

  if !Rails.env.test? && CmsRails::Application.sso_callback_url
    match 'sso/new' => 'sso#new', :as => 'login'
    match CmsRails::Application.sso_callback_url => "sso#callback"
    match 'sso/destroy' => 'sso#destroy', :as => 'logout'
  else
    match 'login' => 'user_sessions#login', :as => 'login'
    match 'user_sessions/destroy' => 'user_sessions#destroy', :as => 'logout'
    match 'user_sessions/create' => 'user_sessions#create'
  end

  match 'document/:action' => 'document'

  match 'evidence/index' => 'evidence#index'
  match 'evidence/show_closed_control/:system_id/:control_id' => 'evidence#show_closed_control'
  match 'evidence/show_control/:system_id/:control_id' => 'evidence#show_control'
  match 'evidence/new/:system_id/:control_id/:descriptor_id' => 'evidence#new'
  match 'evidence/new_gdoc/:system_id/:control_id/:descriptor_id' => 'evidence#new_gdoc'
  match 'evidence/attach/:system_id/:control_id/:descriptor_id' => 'evidence#attach'
  match 'evidence/show/:document_id' => 'evidence#show'
  match 'evidence/update/:document_id' => 'evidence#update'
  match 'evidence/destroy/:system_id/:control_id/:document_id' => 'evidence#destroy'
  match 'evidence/review/:document_id/:value' => 'evidence#review'

  root :to => "welcome#index"
  match 'about' => 'welcome#about', :as => 'about'
  match 'placeholder' => 'welcome#placeholder', :as => 'placeholder'
  match 'login_dispatch' => 'welcome#login_dispatch', :as => 'login_dispatch'
  get 'welcome/reload'

end

app/models/risky_attribute.rb
class RiskyAttribute < ActiveRecord::Base
  include AuthoredModel
  include SluggedModel
  include SearchableModel
  include AuthorizedModel
  include RelatedModel
  include SanitizableAttributes
  include DatedModel

  TYPE_STRINGS = %w(OrgGroup Product Facility Market Project DataAsset Process System)

  attr_accessible :title, :slug, :description, :url, :version, :type_string, :start_date, :stop_date

  has_many :object_people, :as => :personable, :dependent => :destroy
  has_many :people, :through => :object_people

  has_many :object_documents, :as => :documentable, :dependent => :destroy
  has_many :documents, :through => :object_documents

  # Many to many with Risk
  has_many :risk_risky_attributes, :dependent => :destroy
  has_many :risks, :through => :risk_risky_attributes

  is_versioned_ext

  sanitize_attributes :description

  validates :title, :type_string,
    :presence => { :message => "needs a value" }
  validate :type_string_cannot_change_if_relationships_exist

  def self.type_strings
    TYPE_STRINGS
  end

  def type_string_cannot_change_if_relationships_exist
    if changed_attributes['type_string'].present? && !can_change_type_string?
      errors.add(:type_string, "Cannot change Type when Relationships exist")
    end
  end

  def can_change_type_string?
    new_record? || attributed_objects.count == 0
  end

  def default_slug_prefix
    'RA'
  end

  def display_name
    slug
  end

  def attributed_objects
    Relationship.where(
      :destination_type => self.class.name,
      :destination_id => id,
    ).includes(:source).map(&:source)
  end
end

app/controllers/risky_attributes_controller.rb
# Handle RiskyAttributes
class RiskyAttributesController < BaseObjectsController

#  access_control :acl do
#    # FIXME: Implement real authorization
#
#    allow :superuser
#
#    actions :index do
#      allow :read, :read_risky_attribute
#    end
#
#    actions :new, :create do
#      allow :create, :create_risky_attribute
#    end
#
#    actions :edit, :update do
#      allow :update, :update_risky_attribute, :of => :risky_attribute
#    end
#
#    actions :show, :tooltip do
#      allow :read, :read_risky_attribute, :of => :risky_attribute
#    end
#
#  end
  
 before_filter :check_risk_authorization

  layout 'dashboard'

  def index
    object_set = model_class
    if params[:s].present?
      if object_set.respond_to?(:fulltext_search)
        object_set = object_set.fulltext_search(params[:s])
      else
        object_set = object_set.db_search(params[:s])
      end
    end
    if params[:type_string].present?
      object_set = object_set.where(:type_string => params[:type_string])
    end
    object_set = allowed_objs(object_set.all, :read)
    set_objects(object_set)

    respond_to do |format|
      format.html do
        if params[:quick]
          render :partial => 'quick', :locals => { :quick_result => params[:qr]}
        end
      end
      format.json do
        render :json => objects_as_json
      end
    end
  end

  private

    def risky_attribute_params
      risky_attribute_params = params[:risky_attribute] || {}
      %w(start_date stop_date).each do |field|
        parse_date_param(risky_attribute_params, field)
      end
      risky_attribute_params
    end
    
end

app/views/risky_attributes/_attributed_object.haml
-# locals: instance, id_prefix, seen_ids, is_root
-#instance = risky_attribute
-model_underscore = instance.class.name.underscore

-is_root = false if local_assigns[:is_root].nil?

-seen_ids = [] if local_assigns[:seen_ids].nil?
-id_prefix = "instance-#{instance.class.name.underscore}-#{instance.id}" if local_assigns[:id_prefix].nil?

-seen_this = seen_ids.include?(instance.id)

-expand_this = false #(!seen_this && sub_objects.count > 0)

-summary_toggle_target = "#{id_prefix}-summary"
-objects_toggle_target = "#{id_prefix}-objects"

-main_toggle_target = expand_this ? objects_toggle_target : summary_toggle_target

%li{ :class => instance.class.name.downcase, :'data-object-id' => instance.id}
  .item-main
    .openclose{ :class => 'lastchild' }
    .item-title
      .row-fluid
        =render :partial => 'object_leaf', :locals => { :instance => instance, :notes_attr => "" }
      .item-actions
        %a.btn.btn-mini.halfopacity{ "rel" => "tooltip", "data-placement" => "left", "title" => "Edit this object", 'data-modal-class' => 'modal-wide', 'data-form-target' => 'refresh', "data-toggle" => "modal-ajax-form", :href => url_for(:id => instance.id, :action => :edit, :controller => model_underscore.pluralize, :only_path => true) }
          %i.grcicon-edit
        -if !is_root
          %a.btn.btn-mini.halfopacity{ "rel" => "tooltip", "data-placement" => "left", "title" => "Go to this object's page", :href => url_for(:id => instance.id, :action => :show, :controller => model_underscore.pluralize, :only_path => true) }
            %i.grcicon-goto

app/views/risky_attributes/_business_objects.haml
-# locals: risky_attribute
-model_name = controller_name.singularize
-model_title = controller_name.singularize.titleize

-content_for :widget_title do
  #{risky_attribute.type_string.pluralize.titleize} with this Risky Attribute

-content_for :widget_help, "#{model_name}_business_objects"

-content_for :widget_id, "#{model_name}_business_objects_widget"

-content_for :widget_buttons do
  .filter
    .row-fluid
      .span12
        .pull-right
          %a.widgetbtn.btn.btn-add{ :rel => "tooltip", :"data-placement" => "left", :title => "Link #{risky_attribute.type_string.pluralize.titleize} to this Risky Attribute", :'data-modal-class' => 'modal-wide', :'data-modal-reset' => 'reset', :'data-list-target' => 'refresh', :"data-toggle" => "modal-ajax-relationship-selector", :href => list_edit_flow_relationships_path(:object_id => risky_attribute.id, :object_type => risky_attribute.class.name, :related_model => risky_attribute.type_string, :related_side => 'source', :relationship_type => "#{risky_attribute.type_string.underscore}_has_risky_attribute") }
            %i.grcicon-link-white
            =risky_attribute.type_string.titleize
            

%ul.tree-structure
  -risky_attribute.attributed_objects.each do |object|
    =render :partial => "attributed_object",
            :locals => { :instance => object }

app/views/risky_attributes/_form.haml
-model_name = controller_name.singularize
-model_title = model_name.titleize
-content_for :modal_title do
  -if f.object.new_record?
    Create a new #{model_title}
  -else
    Edit #{model_title}

-if !f.object.new_record?
  -content_for :modal_delete_path, method("delete_flow_#{model_name}_path").call(f.object)

.row-fluid
  =wrapped_text_field f, :span6, :title, :placeholder => 'Enter title', :label_name => 'Title <span class="required">*</span>'.html_safe
  .span6
    .row-fluid
      =wrapped_text_field f, :span12, :slug, :label_name => 'Code (autofill)', :placeholder => "#{f.object.default_slug_prefix.upcase}-XXXX"
      -#=wrapped_text_field f, :span6, :version, :placeholder => '1.1.1'
.row-fluid
  =wrapped_text_area f, :span6, :description, :class => 'double wysihtml5', :wrapper_div_class => 'wysiwyg-area', :placeholder => 'Enter description here'
  .span6
    .row-fluid
      =wrapped_date_field f, :span6, :start_date, :class => 'date', :label_name => 'Effective Date', :placeholder => 'MM/DD/YYYY'
      =wrapped_date_field f, :span6, :stop_date, :class => 'date', :label_name => 'Stop Date', :placeholder => 'MM/DD/YYYY'
    .row-fluid
      -if params[:force_type_string].present? || !f.object.can_change_type_string?
        .span6
          %label Type
          =f.hidden_field :type_string
          =hidden_field_tag :force_type_string, params[:force_type_string]
          .item.oneline=f.object.type_string
      -else
        =wrapped_select f, :span6, :type_string, RiskyAttribute.type_strings.map{ |t| [t.titleize, t] }, :selected => (f.object.type_string), :label_name => 'Type'

.row-fluid
  =wrapped_text_field f, :span6, :url, :label_name => 'Direct URL (optional)', :placeholder => 'http://www.example.com/'

=render :partial => "shared/wysihtml5"

app/views/risky_attributes/_main.haml
-model_name = controller_name.singularize
-model_title = controller_name.singularize.titleize
-instance = instance_variable_get("@" + model_name)
-content_for :widget_title do
  Risks associated with this Attribute

-content_for :widget_help, "#{model_name}_main"

-content_for :widget_id, "#{model_name}_main_widget"

-content_for :widget_buttons do
  .filter
    .row-fluid
      .span12
        .pull-right
          %a.widgetbtn.btn.btn-add{ :href => list_edit_flow_risk_risky_attributes_path(:risky_attribute_id => risky_attribute.id), :'data-toggle' => 'modal-ajax-relationship-selector', :'data-modal-reset' => 'reset', :'data-list-target' => 'refresh', :rel => 'tooltip', :'data-placement' => 'left', :title => 'Link risks to this attribute', :'data-modal-class' => 'modal-wide' }
            %i.grcicon-link-white
            Risk

.action-items
  %a.expandAll.btn.btn-mini{:href => "#", :rel => "tooltip", :title => "Expand all"}
    %i.grcicon-wide-black
  %a.shrinkAll.btn.btn-mini{:href => "#", :rel => "tooltip", :title => "Collapse all"}
    %i.grcicon-normal-black

%ul.tree-structure
  -risks.each_with_index do |risk, i|
    -id_prefix = "risk-#{i}"
    -summary_toggle_target = "#{id_prefix}-summary"

    %li{ :class => risk.class.name.downcase}
      .item-main
        .openclose{ :class => 'lastchild' }
        .item-title
          .row-fluid
            =render :partial => 'object_leaf', :locals => { :instance => risk }
          .item-actions
            %a.btn.btn-mini.halfopacity{ "rel" => "tooltip", "data-placement" => "left", "title" => "Go to this object's page", :href => flow_risk_path(risk.id) }
              %i.grcicon-goto

app/views/risky_attributes/show.haml
-model_name = controller_name.singularize.underscore
-model_title = model_name.titleize
-instance = instance_variable_get("@" + model_name)

-@title = "GRC #{model_title}: #{instance.title}"

-content_for :header do
  %ul.breadcrumbs
    %li=link_to 'dashboard', programs_dash_path
    %li= instance.slug
    
  %h1.risk
    .grcobject.risk{:rel => "tooltip", :'data-placement'=>"bottom", :title => "Attribute"}
      %i.grcicon-attribute
    =instance.title

-content_for :page_help, model_name

-content_for :subheader_extras do
  %ul.actions.pull-right
    %li
      %a{ :href => method("edit_flow_#{model_name}_path").call(instance), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'refresh', :'data-modal-class' => 'modal-wide', :title => "Edit #{model_title}" }
        %i.grcicon-edit
        %span Edit #{model_title}

-content_for :subheader_plus do
  %a.navbarplus.fltrt{ :href => method("new_flow_#{model_name}_path").call(), :'data-toggle' => 'modal-ajax-form', :'data-modal-reset' => 'reset', :'data-form-target' => 'redirect', :'data-modal-class' => 'modal-wide'}

.container-fluid
  #risky_attributes_columns.row-fluid{ :'data-resize' => "true" }
    #main_column.span8.widget-area
      =render :partial => "main",
              :layout => 'layouts/widget_box',
              :locals => { model_name.to_sym => instance, :risks => instance.risks, :widget_class => "risk" }
  
      =render :partial => "business_objects",
            :layout => 'layouts/widget_box',
            :locals => { model_name.to_sym => instance, :widget_class => "risk" }
          
    #right_column.span4.widget-area
      =render :partial => "info",
              :layout => 'layouts/widget_box',
              :locals => { model_name.to_sym => instance, :widget_class => "risk" }
              
      =render :partial => "more_info",
              :layout => 'layouts/widget_box',
              :locals => { model_name.to_sym => instance, :widget_class => 'related business' }

app/views/risky_attributes/tooltip.haml
=render :partial => "shared/tooltip_model"